# Verbatim port of SeedData/categories.json.
# Each dict: {name, short_name, is_area_category, children: [...]}
CATEGORIES = [
    {"name": "Area", "short_name": None, "is_area_category": True, "children": [
        {"name": "Building", "short_name": None, "is_area_category": True, "children": [
            {"name": "Apartment",    "short_name": None, "is_area_category": True,  "children": []},
            {"name": "Balcony",      "short_name": None, "is_area_category": True,  "children": []},
            {"name": "Carport",      "short_name": None, "is_area_category": True,  "children": []},
            {"name": "Ceiling Area", "short_name": None, "is_area_category": False, "children": []},
            {"name": "Facade Area",  "short_name": None, "is_area_category": True,  "children": []},
            {"name": "Floor",        "short_name": None, "is_area_category": True,  "children": []},
            {"name": "Floor Area",   "short_name": None, "is_area_category": False, "children": []},
            {"name": "Garage",       "short_name": None, "is_area_category": True,  "children": []},
            {"name": "House",        "short_name": None, "is_area_category": True,  "children": []},
            {"name": "Other Area",   "short_name": None, "is_area_category": False, "children": []},
            {"name": "Roof Area",    "short_name": None, "is_area_category": False, "children": []},
            {"name": "Room",         "short_name": None, "is_area_category": True,  "children": []},
            {"name": "Wall Area",    "short_name": None, "is_area_category": False, "children": []},
        ]},
        {"name": "Outdoor Area", "short_name": None, "is_area_category": True, "children": [
            {"name": "Driveway Area", "short_name": None, "is_area_category": True, "children": []},
            {"name": "Entrance Area", "short_name": None, "is_area_category": True, "children": []},
            {"name": "Garden Area",   "short_name": None, "is_area_category": True, "children": []},
            {"name": "Garden Shed",   "short_name": None, "is_area_category": True, "children": []},
            {"name": "Greenhouse",    "short_name": None, "is_area_category": True, "children": []},
            {"name": "Other Area",    "short_name": None, "is_area_category": True, "children": []},
            {"name": "Parking Space", "short_name": None, "is_area_category": True, "children": []},
            {"name": "Pool Area",     "short_name": None, "is_area_category": True, "children": []},
            {"name": "Terrace Area",  "short_name": None, "is_area_category": True, "children": []},
        ]},
    ]},
    {"name": "Building Material", "short_name": None, "is_area_category": False, "children": [
        {"name": "Door",           "short_name": None, "is_area_category": False, "children": []},
        {"name": "Flooring",       "short_name": None, "is_area_category": False, "children": []},
        {"name": "Pipe",           "short_name": None, "is_area_category": False, "children": []},
        {"name": "Roof",           "short_name": None, "is_area_category": False, "children": []},
        {"name": "Roof Drainage",  "short_name": None, "is_area_category": False, "children": []},
        {"name": "Stairs",         "short_name": None, "is_area_category": False, "children": []},
        {"name": "Wall",           "short_name": None, "is_area_category": False, "children": []},
        {"name": "Window",         "short_name": None, "is_area_category": False, "children": [
            {"name": "Shading",    "short_name": None, "is_area_category": False, "children": []},
        ]},
        {"name": "Other",          "short_name": None, "is_area_category": False, "children": []},
    ]},
    {"name": "Electrical", "short_name": None, "is_area_category": False, "children": [
        {"name": "Cable",        "short_name": None, "is_area_category": False, "children": []},
        {"name": "Conduit",      "short_name": None, "is_area_category": False, "children": []},
        {"name": "Distribution Board", "short_name": None, "is_area_category": False, "children": [
            {"name": "Circuit Breaker", "short_name": None, "is_area_category": False, "children": []},
            {"name": "Panel Section",   "short_name": None, "is_area_category": False, "children": [
                {"name": "Panel Field", "short_name": None, "is_area_category": False, "children": []},
                {"name": "Panel Row",   "short_name": None, "is_area_category": False, "children": []},
            ]},
            {"name": "Terminal Block",  "short_name": None, "is_area_category": False, "children": []},
            {"name": "Other",           "short_name": None, "is_area_category": False, "children": []},
        ]},
        {"name": "Home Automation", "short_name": None, "is_area_category": False, "children": [
            {"name": "Actuator",        "short_name": None, "is_area_category": False, "children": []},
            {"name": "Control Panel",   "short_name": None, "is_area_category": False, "children": []},
            {"name": "Data Cable",      "short_name": None, "is_area_category": False, "children": []},
            {"name": "Gateway",         "short_name": None, "is_area_category": False, "children": []},
            {"name": "Motion Detector", "short_name": None, "is_area_category": False, "children": []},
            {"name": "Push Button",     "short_name": None, "is_area_category": False, "children": []},
            {"name": "Sensor",          "short_name": None, "is_area_category": False, "children": []},
            {"name": "Other",           "short_name": None, "is_area_category": False, "children": []},
        ]},
        {"name": "Junction Box",  "short_name": None, "is_area_category": False, "children": []},
        {"name": "Lighting",      "short_name": None, "is_area_category": False, "children": []},
        {"name": "Meter",         "short_name": None, "is_area_category": False, "children": []},
        {"name": "Outlet",        "short_name": None, "is_area_category": False, "children": []},
        {"name": "Photovoltaics", "short_name": "PV", "is_area_category": False, "children": [
            {"name": "Battery Storage", "short_name": None, "is_area_category": False, "children": []},
            {"name": "Inverter",        "short_name": None, "is_area_category": False, "children": []},
            {"name": "Solar Panel",     "short_name": None, "is_area_category": False, "children": []},
            {"name": "Other",           "short_name": None, "is_area_category": False, "children": []},
        ]},
        {"name": "Switch",        "short_name": None, "is_area_category": False, "children": []},
        {"name": "Wallbox",       "short_name": None, "is_area_category": False, "children": []},
        {"name": "Other",         "short_name": None, "is_area_category": False, "children": []},
    ]},
    {"name": "Heating, Ventilation & Air Conditioning", "short_name": "HVAC", "is_area_category": False, "children": [
        {"name": "Air Conditioning", "short_name": None, "is_area_category": False, "children": []},
        {"name": "Heating",          "short_name": None, "is_area_category": False, "children": []},
        {"name": "Ventilation",      "short_name": None, "is_area_category": False, "children": []},
    ]},
    {"name": "Plumbing", "short_name": None, "is_area_category": False, "children": [
        {"name": "Drainage",          "short_name": None, "is_area_category": False, "children": []},
        {"name": "Gas Supply",        "short_name": None, "is_area_category": False, "children": []},
        {"name": "Sanitary Fixtures", "short_name": None, "is_area_category": False, "children": []},
        {"name": "Water Supply",      "short_name": None, "is_area_category": False, "children": []},
    ]},
    {"name": "IT & Communications", "short_name": "ITC", "is_area_category": False, "children": [
        {"name": "Network",         "short_name": None, "is_area_category": False, "children": []},
        {"name": "Telephony",       "short_name": None, "is_area_category": False, "children": []},
        {"name": "TV & Multimedia", "short_name": None, "is_area_category": False, "children": []},
    ]},
    {"name": "Security", "short_name": None, "is_area_category": False, "children": [
        {"name": "Access Control", "short_name": None, "is_area_category": False, "children": []},
        {"name": "Burglar Alarm",  "short_name": None, "is_area_category": False, "children": [
            {"name": "Perimeter Protection", "short_name": None, "is_area_category": False, "children": []},
        ]},
        {"name": "Fire Protection", "short_name": None, "is_area_category": False, "children": [
            {"name": "Fire Suppression", "short_name": None, "is_area_category": False, "children": []},
            {"name": "Smoke Detector",   "short_name": None, "is_area_category": False, "children": []},
        ]},
        {"name": "Surveillance",   "short_name": None, "is_area_category": False, "children": []},
    ]},
    {"name": "Landscaping", "short_name": None, "is_area_category": False, "children": [
        {"name": "Decking",    "short_name": None, "is_area_category": False, "children": []},
        {"name": "Fence",      "short_name": None, "is_area_category": False, "children": []},
        {"name": "Irrigation", "short_name": None, "is_area_category": False, "children": [
            {"name": "Distribution", "short_name": None, "is_area_category": False, "children": []},
            {"name": "Sprinkler",    "short_name": None, "is_area_category": False, "children": []},
        ]},
        {"name": "Paving",     "short_name": None, "is_area_category": False, "children": []},
        {"name": "Planting",   "short_name": None, "is_area_category": False, "children": []},
        {"name": "Pool",       "short_name": None, "is_area_category": False, "children": []},
        {"name": "Other",      "short_name": None, "is_area_category": False, "children": []},
    ]},
    {"name": "Health", "short_name": None, "is_area_category": False, "children": [
        {"name": "First Aid",       "short_name": None, "is_area_category": False, "children": []},
        {"name": "Medical Devices", "short_name": None, "is_area_category": False, "children": []},
        {"name": "Medications",     "short_name": None, "is_area_category": False, "children": []},
    ]},
    {"name": "Household", "short_name": None, "is_area_category": False, "children": [
        {"name": "Appliances",     "short_name": None, "is_area_category": False, "children": []},
        {"name": "Electronics",    "short_name": None, "is_area_category": False, "children": []},
        {"name": "Furnishings",    "short_name": None, "is_area_category": False, "children": []},
        {"name": "Provisions",     "short_name": None, "is_area_category": False, "children": []},
        {"name": "Toys & Hobbies", "short_name": None, "is_area_category": False, "children": []},
        {"name": "Valuables",      "short_name": None, "is_area_category": False, "children": []},
        {"name": "Other",          "short_name": None, "is_area_category": False, "children": []},
    ]},
    {"name": "Sports & Leisure", "short_name": None, "is_area_category": False, "children": []},
    {"name": "Vehicles", "short_name": None, "is_area_category": False, "children": [
        {"name": "Bicycle",    "short_name": None, "is_area_category": False, "children": []},
        {"name": "Car",        "short_name": None, "is_area_category": False, "children": []},
        {"name": "E-Bike",     "short_name": None, "is_area_category": False, "children": []},
        {"name": "Motorcycle", "short_name": None, "is_area_category": False, "children": []},
        {"name": "Trailer",    "short_name": None, "is_area_category": False, "children": []},
        {"name": "Other",      "short_name": None, "is_area_category": False, "children": []},
    ]},
    {"name": "Tools",  "short_name": None, "is_area_category": False, "children": []},
    {"name": "Other",  "short_name": None, "is_area_category": False, "children": []},
]
